# Generated by Django 5.1.6 on 2025-02-14 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_alter_category_created_by_alter_category_updated_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='published',
            field=models.BooleanField(default=True),
        ),
    ]
